version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    container_name: backend
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/memoriesDB
    depends_on:
      - mongo

  client:
    build: ./client
    container_name: frontend
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    depends_on:
      - server

volumes:
  mongo_data:
